import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div
      className="relative min-h-screen py-16 px-4"
      style={{
        backgroundImage: "url('/auth-back.png')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        backgroundAttachment: "fixed",
      }}
    >
      <div className="absolute inset-0 bg-white/40" />

      {/* Elsa — absolutely positioned on the left */}
      <div className="hidden lg:block fixed left-0 top-1/2 -translate-y-1/2 z-20 pointer-events-none">
        <Image src="/pose9.png" alt="Elsa" width={320} height={420} className="object-contain" />
      </div>

      <div className="max-w-3xl mx-auto relative z-10">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-[#6B7280] hover:text-[#312E81] transition mb-6 bg-white/50 backdrop-blur rounded-full px-4 py-2 border border-white/40">
          <ArrowLeft size={16} /> Back to Home
        </Link>

        <div className="rounded-[28px] border border-white/45 px-6 lg:px-10 py-8 lg:py-10"
          style={{
            background: "rgba(255,255,255,0.22)",
            backdropFilter: "blur(22px)",
            WebkitBackdropFilter: "blur(22px)",
            boxShadow: "0 20px 60px rgba(167,139,250,0.12)",
          }}>
          <h1 className="font-heading text-3xl lg:text-4xl font-bold text-[#312E81] mb-6">Terms of Service</h1>
          <p className="text-sm text-[#6B7280] mb-8">Last updated: August 2026</p>

          <div className="space-y-6 text-[#312E81] text-sm leading-7">
            <section>
              <h2 className="font-heading text-lg font-bold mb-2">1. Acceptance of Terms</h2>
              <p className="text-[#6B7280]">By using BloomLab, you agree to these terms. If you do not agree, please do not use the platform.</p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">2. Your Account</h2>
              <ul className="list-disc pl-5 space-y-1 text-[#6B7280]">
                <li>You are responsible for maintaining the security of your account.</li>
                <li>You must provide accurate information when creating an account.</li>
                <li>You may not share your account credentials with others.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">3. Use of the Platform</h2>
              <p className="text-[#6B7280]">BloomLab is designed for learning and project building. You agree to:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-[#6B7280]">
                <li>Use the AI mentor (Elsa) for educational purposes only.</li>
                <li>Not abuse, spam, or attempt to break the platform.</li>
                <li>Not upload harmful, illegal, or offensive content.</li>
                <li>Respect other learners and their projects.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">4. Intellectual Property</h2>
              <ul className="list-disc pl-5 space-y-1 text-[#6B7280]">
                <li><strong>Your projects:</strong> You own 100% of the code and projects you build on BloomLab.</li>
                <li><strong>BloomLab content:</strong> The platform design, AI prompts, and learning methodology are property of BloomLab.</li>
                <li><strong>AI-generated content:</strong> Lessons generated by Elsa are for your personal learning use.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">5. Limitations</h2>
              <p className="text-[#6B7280]">BloomLab is provided "as is" for educational purposes. We do not guarantee:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-[#6B7280]">
                <li>Uninterrupted access to the platform.</li>
                <li>100% accuracy of AI-generated content.</li>
                <li>Specific learning outcomes or results.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">6. Account Termination</h2>
              <p className="text-[#6B7280]">We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time.</p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">7. Changes to Terms</h2>
              <p className="text-[#6B7280]">We may update these terms. Significant changes will be communicated via email or platform notification.</p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-bold mb-2">8. Contact</h2>
              <p className="text-[#6B7280]">For questions about these terms:</p>
              <a href="mailto:abruptessence@gmail.com" className="text-[#8B5CF6] hover:underline font-semibold">abruptessence@gmail.com</a>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}